import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';

export const createFamilyTreeStyles = (colors: any, isDarkMode?: boolean) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: isDarkMode ? colors.background : '#FAF8F3', // Match Profile soft beige background
  },
  backgroundGradient: {
    flex: 1,
    backgroundColor: isDarkMode ? colors.background : '#FAF8F3', // Match Profile background
  },
  scrollContent: {
    paddingBottom: 120,
  },
  header: {
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 16,
  },
  title: {
    fontSize: 32,
    fontFamily: 'Satoshi-Variable',
    fontWeight: '700',
    color: isDarkMode ? colors.text : '#1F2937', // Match Profile text color
    letterSpacing: -0.8,
  },
  subtitle: {
    fontSize: 16,
    fontFamily: 'Satoshi-Variable',
    color: colors.textSecondary,
    marginTop: 4,
  },
  familyNameContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    gap: 8,
  },
  familyName: {
    fontSize: 24,
    fontFamily: 'Satoshi-Variable',
    fontWeight: '700',
    color: Colors.primary,
    letterSpacing: -0.4,
  },
  familyNameLabel: {
    fontSize: 18,
    fontFamily: 'Satoshi-Variable',
    fontWeight: '600',
    color: isDarkMode ? colors.textSecondary : '#6B7280',
    letterSpacing: -0.2,
  },
  invitationBadge: {
    position: 'absolute',
    top: 24,
    right: 24,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.card,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  badge: {
    position: 'absolute',
    top: -2,
    right: -2,
    backgroundColor: Colors.primary,
    width: 18,
    height: 18,
    borderRadius: 9,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: colors.card,
  },
  badgeText: {
    color: 'white',
    fontSize: 10,
    fontFamily: 'Satoshi-Variable',
    fontWeight: 'bold',
  },
  section: {
    paddingHorizontal: 24,
    marginTop: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
    flexWrap: 'wrap',
    gap: 12,
  },
  sectionTitle: {
    fontSize: 20,
    fontFamily: 'Satoshi-Variable',
    fontWeight: '700',
    color: isDarkMode ? colors.text : '#1F2937',
    letterSpacing: -0.3,
  },
  actionButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  inviteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: isDarkMode ? colors.surface : '#FFFFFF',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    gap: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  inviteButtonText: {
    fontSize: 14,
    fontFamily: 'Satoshi-Variable',
    fontWeight: '600',
    color: Colors.primary,
  },
  addChildButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: isDarkMode ? colors.surface : '#FFFFFF',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    gap: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  addChildButtonText: {
    fontSize: 14,
    fontFamily: 'Satoshi-Variable',
    fontWeight: '600',
    color: Colors.primary,
  },
  memberCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: isDarkMode ? colors.card : '#F9FAFB', // Match Profile card background
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  skeletonCard: {
    opacity: 1,
  },
  memberAvatar: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: `${Colors.primary}15`,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
    overflow: 'hidden',
  },
  memberAvatarImage: {
    width: '100%',
    height: '100%',
  },
  memberInitials: {
    fontSize: 20,
    fontFamily: 'Satoshi-Variable',
    fontWeight: '700',
    color: Colors.primary,
    letterSpacing: 0.5,
  },
  skeletonAvatar: {
    backgroundColor: isDarkMode ? colors.surfaceSecondary : '#E5E7EB',
  },
  skeletonName: {
    width: 120,
    height: 18,
    borderRadius: 8,
    backgroundColor: isDarkMode ? colors.surfaceSecondary : '#E5E7EB',
    marginBottom: 8,
  },
  skeletonRelation: {
    width: 80,
    height: 14,
    borderRadius: 6,
    backgroundColor: isDarkMode ? colors.surfaceSecondary : '#E5E7EB',
  },
  skeletonAction: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: isDarkMode ? colors.surfaceSecondary : '#E5E7EB',
  },
  memberInfo: {
    flex: 1,
  },
  memberNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  memberName: {
    fontSize: 17,
    fontFamily: 'Satoshi-Variable',
    fontWeight: '700',
    color: isDarkMode ? colors.text : '#1F2937', // Match Profile text color
    letterSpacing: -0.2,
  },
  youLabel: {
    fontSize: 12,
    fontFamily: 'Satoshi-Variable',
    color: colors.textSecondary,
    fontStyle: 'italic',
  },
  memberMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 4,
  },
  relationTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: isDarkMode ? colors.surfaceSecondary : '#F3F4F6',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    alignSelf: 'flex-start',
  },
  relationText: {
    fontSize: 12,
    fontFamily: 'Satoshi-Variable',
    fontWeight: '600',
    letterSpacing: 0.1,
  },
  memberEmail: {
    fontSize: 13,
    fontFamily: 'Satoshi-Variable',
    color: colors.textSecondary,
  },
  memberActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  viewRecordsButton: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: isDarkMode ? colors.surfaceSecondary : '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  kickButton: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  noFamilyContainer: {
    marginHorizontal: 24,
    marginTop: 48,
    padding: 40,
    alignItems: 'center',
    backgroundColor: isDarkMode ? colors.card : '#F9FAFB', // Match Profile card background
    borderRadius: 24,
    borderWidth: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  noFamilyIcon: {
    width: 96,
    height: 96,
    borderRadius: 24,
    backgroundColor: `${Colors.primary}15`,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
  },
  noFamilyTitle: {
    fontSize: 24,
    fontFamily: 'Satoshi-Variable',
    fontWeight: '700',
    color: isDarkMode ? colors.text : '#1F2937', // Match Profile text color
    marginBottom: 12,
    letterSpacing: -0.4,
  },
  noFamilyDescription: {
    fontSize: 15,
    fontFamily: 'Satoshi-Variable',
    color: isDarkMode ? colors.textSecondary : '#6B7280', // Lighter secondary text
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 24,
  },
  createFamilyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.primary,
    paddingHorizontal: 28,
    paddingVertical: 16,
    borderRadius: 16,
    gap: 10,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  createFamilyButtonText: {
    color: 'white',
    fontSize: 16,
    fontFamily: 'Satoshi-Variable',
    fontWeight: 'bold',
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: isDarkMode ? colors.card : '#F9FAFB', // Match Profile card background
    padding: 18,
    borderRadius: 16,
    borderWidth: 0,
    gap: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  actionButtonText: {
    fontSize: 16,
    fontFamily: 'Satoshi-Variable',
    fontWeight: '500',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    fontFamily: 'Satoshi-Variable',
    color: colors.textSecondary,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: isDarkMode ? colors.background : '#FAF8F3', // Match Profile background
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 24,
    borderBottomWidth: 1,
    borderBottomColor: isDarkMode ? colors.border : '#E5E7EB',
  },
  modalTitle: {
    fontSize: 24,
    fontFamily: 'Satoshi-Variable',
    fontWeight: '700',
    color: colors.text,
    letterSpacing: -0.4,
  },
  closeButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: isDarkMode ? colors.surface : '#F9FAFB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalContent: {
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 40,
  },
  inputLabel: {
    fontSize: 15,
    fontFamily: 'Satoshi-Variable',
    fontWeight: '600',
    color: isDarkMode ? colors.text : '#1F2937', // Match Profile text color
    marginBottom: 10,
    letterSpacing: -0.1,
  },
  textInput: {
    backgroundColor: isDarkMode ? colors.surface : '#F9FAFB', // Match Profile card background
    borderWidth: 0,
    borderRadius: 16,
    padding: 16,
    fontSize: 16,
    fontFamily: 'Satoshi-Variable',
    color: colors.text,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.02,
    shadowRadius: 4,
    elevation: 1,
  },
  submitButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 16,
    borderRadius: 16,
    backgroundColor: Colors.primary,
    marginTop: 16,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  submitButtonText: {
    fontSize: 16,
    color: 'white',
    fontFamily: 'Satoshi-Variable',
    fontWeight: 'bold',
  },
  ageNoticeCard: {
    backgroundColor: isDarkMode ? colors.surface : '#F9FAFB', // Match Profile card background
    borderRadius: 16,
    padding: 16,
    marginBottom: 24,
    borderLeftWidth: 4,
    borderLeftColor: Colors.primary,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.02,
    shadowRadius: 4,
    elevation: 1,
  },
  ageNoticeTitle: {
    fontSize: 15,
    fontFamily: 'Satoshi-Variable',
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 4,
  },
  ageNoticeText: {
    fontSize: 14,
    fontFamily: 'Satoshi-Variable',
    color: colors.textSecondary,
    lineHeight: 20,
  },
  relationSelector: {
    marginBottom: 16,
  },
  relationOption: {
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 16,
    marginRight: 10,
    backgroundColor: isDarkMode ? colors.surface : '#F9FAFB', // Match Profile card background
    borderWidth: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.02,
    shadowRadius: 4,
    elevation: 1,
  },
  relationOptionSelected: {
    backgroundColor: `${Colors.primary}20`,
    borderColor: Colors.primary,
  },
  relationOptionText: {
    fontSize: 14,
    fontFamily: 'Satoshi-Variable',
    fontWeight: '500',
    color: colors.text,
  },
  relationOptionTextSelected: {
    color: Colors.primary,
  },
  invitationCard: {
    backgroundColor: isDarkMode ? colors.card : '#F9FAFB', // Match Profile card background
    borderRadius: 16,
    padding: 18,
    marginBottom: 12,
    borderWidth: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  invitationInfo: {
    flex: 1,
  },
  invitationTitle: {
    fontSize: 18,
    fontFamily: 'Satoshi-Variable',
    fontWeight: '700',
    color: isDarkMode ? colors.text : '#1F2937', // Match Profile text color
    marginBottom: 6,
    letterSpacing: -0.2,
  },
  invitationDescription: {
    fontSize: 14,
    fontFamily: 'Satoshi-Variable',
    color: isDarkMode ? colors.textSecondary : '#6B7280', // Lighter secondary text
    lineHeight: 22,
    marginBottom: 16,
  },
  relationHighlight: {
    color: Colors.primary,
    fontWeight: 'bold',
  },
  invitationActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 16,
  },
  acceptButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 16,
    backgroundColor: Colors.medical.green,
    shadowColor: Colors.medical.green,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  declineButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 16,
    backgroundColor: isDarkMode ? colors.surface : '#F9FAFB', // Match Profile card background
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.02,
    shadowRadius: 4,
    elevation: 1,
  },
  childModalDescription: {
    fontSize: 15,
    fontFamily: 'Satoshi-Variable',
    color: colors.textSecondary,
    lineHeight: 22,
    marginBottom: 24,
    padding: 16,
    backgroundColor: isDarkMode ? colors.surface : '#F9FAFB', // Match Profile card background
    borderRadius: 16,
    borderLeftWidth: 4,
    borderLeftColor: Colors.primary,
  },
  multilineInput: {
    height: 100,
    textAlignVertical: 'top',
  },
  dropdownButton: {
    borderWidth: 0,
    borderRadius: 16,
    padding: 16,
    backgroundColor: isDarkMode ? colors.surface : '#F9FAFB', // Match Profile card background
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.02,
    shadowRadius: 4,
    elevation: 1,
  },
  dropdownText: {
    fontSize: 16,
    fontFamily: 'Satoshi-Variable',
    color: colors.text,
  },
  placeholderText: {
    color: colors.textSecondary,
  },
  dropdownArrow: {
    fontSize: 12,
    color: colors.textSecondary,
  },
  dropdownMenu: {
    borderWidth: 0,
    borderRadius: 16,
    backgroundColor: isDarkMode ? colors.card : '#F9FAFB', // Match Profile card background
    marginTop: 8,
    maxHeight: 150,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    overflow: 'hidden',
  },
  dropdownOption: {
    padding: 16,
    borderBottomWidth: 0,
  },
  dropdownOptionText: {
    fontSize: 16,
    fontFamily: 'Satoshi-Variable',
    color: colors.text,
  },
});