import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';

export const createFamilyTreeStyles = (colors: any) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  backgroundGradient: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 120,
  },
  header: {
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 16,
  },
  title: {
    fontSize: 32,
    fontFamily: 'Satoshi-Variable',
    fontWeight: 'bold',
    color: colors.text,
  },
  subtitle: {
    fontSize: 16,
    fontFamily: 'Satoshi-Variable',
    color: colors.textSecondary,
    marginTop: 4,
  },
  invitationBadge: {
    position: 'absolute',
    top: 24,
    right: 24,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.card,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  badge: {
    position: 'absolute',
    top: -2,
    right: -2,
    backgroundColor: Colors.primary,
    width: 18,
    height: 18,
    borderRadius: 9,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: colors.card,
  },
  badgeText: {
    color: 'white',
    fontSize: 10,
    fontFamily: 'Satoshi-Variable',
    fontWeight: 'bold',
  },
  section: {
    paddingHorizontal: 24,
    marginTop: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 20,
    fontFamily: 'Satoshi-Variable',
    fontWeight: 'bold',
    color: colors.text,
  },
  actionButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  inviteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: `${Colors.primary}1A`,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    gap: 6,
  },
  inviteButtonText: {
    fontSize: 14,
    fontFamily: 'Satoshi-Variable',
    fontWeight: '500',
    color: Colors.primary,
  },
  addChildButton: {
     flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: `${Colors.primary}1A`,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    gap: 6,
  },
  addChildButtonText: {
    fontSize: 14,
    fontFamily: 'Satoshi-Variable',
    fontWeight: '500',
    color: Colors.primary,
  },
  memberCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.card,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  memberAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: `${Colors.primary}20`,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  memberInitials: {
    fontSize: 18,
    fontFamily: 'Satoshi-Variable',
    fontWeight: 'bold',
    color: Colors.primary,
  },
  memberInfo: {
    flex: 1,
  },
  memberNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  memberName: {
    fontSize: 16,
    fontFamily: 'Satoshi-Variable',
    fontWeight: 'bold',
    color: colors.text,
  },
  youLabel: {
    fontSize: 12,
    fontFamily: 'Satoshi-Variable',
    color: colors.textSecondary,
    fontStyle: 'italic',
  },
  memberMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 4,
  },
  relationTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  relationText: {
    fontSize: 13,
    fontFamily: 'Satoshi-Variable',
    fontWeight: '500',
  },
  memberEmail: {
    fontSize: 13,
    fontFamily: 'Satoshi-Variable',
    color: colors.textSecondary,
  },
  memberActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 0,
  },
  viewRecordsButton: {
    padding: 8,
  },
  kickButton: {
    padding: 8,
  },
  noFamilyContainer: {
    marginHorizontal: 24,
    marginTop: 48,
    padding: 32,
    alignItems: 'center',
    backgroundColor: colors.card,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
  },
  noFamilyIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: `${Colors.primary}1A`,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
  },
  noFamilyTitle: {
    fontSize: 22,
    fontFamily: 'Satoshi-Variable',
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 12,
  },
  noFamilyDescription: {
    fontSize: 15,
    fontFamily: 'Satoshi-Variable',
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 24,
  },
  createFamilyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.primary,
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 12,
    gap: 8,
  },
  createFamilyButtonText: {
    color: 'white',
    fontSize: 16,
    fontFamily: 'Satoshi-Variable',
    fontWeight: 'bold',
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.card,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 12,
  },
  actionButtonText: {
    fontSize: 16,
    fontFamily: 'Satoshi-Variable',
    fontWeight: '500',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    fontFamily: 'Satoshi-Variable',
    color: colors.textSecondary,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 24,
  },
  modalTitle: {
    fontSize: 24,
    fontFamily: 'Satoshi-Variable',
    fontWeight: 'bold',
    color: colors.text,
  },
  closeButton: {
    padding: 4,
  },
  modalContent: {
    paddingHorizontal: 24,
    paddingBottom: 24,
  },
  inputLabel: {
    fontSize: 16,
    fontFamily: 'Satoshi-Variable',
    fontWeight: '500',
    color: colors.text,
    marginBottom: 12,
  },
  textInput: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    fontFamily: 'Satoshi-Variable',
    color: colors.text,
    marginBottom: 16,
  },
  submitButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 16,
    borderRadius: 12,
    backgroundColor: Colors.primary,
    marginTop: 16,
  },
  submitButtonText: {
    fontSize: 16,
    color: 'white',
    fontFamily: 'Satoshi-Variable',
    fontWeight: 'bold',
  },
  ageNoticeCard: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 16,
    marginBottom: 24,
  },
  ageNoticeTitle: {
    fontSize: 15,
    fontFamily: 'Satoshi-Variable',
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 4,
  },
  ageNoticeText: {
    fontSize: 14,
    fontFamily: 'Satoshi-Variable',
    color: colors.textSecondary,
    lineHeight: 20,
  },
  relationSelector: {
    marginBottom: 16,
  },
  relationOption: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    marginRight: 8,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  relationOptionSelected: {
    backgroundColor: `${Colors.primary}20`,
    borderColor: Colors.primary,
  },
  relationOptionText: {
    fontSize: 14,
    fontFamily: 'Satoshi-Variable',
    fontWeight: '500',
    color: colors.text,
  },
  relationOptionTextSelected: {
    color: Colors.primary,
  },
  invitationCard: {
    backgroundColor: colors.card,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  invitationInfo: {
    flex: 1,
  },
  invitationTitle: {
    fontSize: 16,
    fontFamily: 'Satoshi-Variable',
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 4,
  },
  invitationDescription: {
    fontSize: 14,
    fontFamily: 'Satoshi-Variable',
    color: colors.textSecondary,
    lineHeight: 20,
  },
  relationHighlight: {
    color: Colors.primary,
    fontWeight: 'bold',
  },
  invitationActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 16,
  },
  acceptButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: Colors.medical.green,
  },
  declineButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: colors.surface,
  },
  childModalDescription: {
    fontSize: 15,
    fontFamily: 'Satoshi-Variable',
    color: colors.textSecondary,
    lineHeight: 22,
    marginBottom: 24,
  },
  multilineInput: {
    height: 100,
    textAlignVertical: 'top',
  },
  dropdownButton: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    padding: 16,
    backgroundColor: colors.surface,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  dropdownText: {
    fontSize: 16,
    fontFamily: 'Satoshi-Variable',
    color: colors.text,
  },
  placeholderText: {
    color: colors.textSecondary,
  },
  dropdownArrow: {
    fontSize: 12,
    color: colors.textSecondary,
  },
  dropdownMenu: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    backgroundColor: colors.card,
    marginTop: 4,
    maxHeight: 150,
  },
  dropdownOption: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  dropdownOptionText: {
    fontSize: 16,
    fontFamily: 'Satoshi-Variable',
    color: colors.text,
  },
});